# Generated by Django 5.1.7 on 2025-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_organizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_organizer',
            field=models.BooleanField(default=False, verbose_name='is organiser'),
        ),
    ]
