# Generated by Django 5.1.7 on 2025-03-17 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_remove_checkincode_event_attendee_and_more'),
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='organizer'),
        ),
        migrations.CreateModel(
            name='BreakawaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum attendees')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakaways', to='events.event', verbose_name='event')),
                ('panelists', models.ManyToManyField(related_name='panelist_sessions', to=settings.AUTH_USER_MODEL, verbose_name='panelists')),
            ],
            options={
                'verbose_name': 'breakaway session',
                'verbose_name_plural': 'breakaway sessions',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('checked_in', models.BooleanField(default=False, verbose_name='checked in')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event', verbose_name='event')),
                ('selected_sessions', models.ManyToManyField(blank=True, related_name='attendees', to='events.breakawaysession', verbose_name='selected sessions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'ordering': ['created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='EventAttendee',
        ),
    ]
