# Generated by Django 5.1.7 on 2025-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_remove_event_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='qr_code_data',
            field=models.UUIDField(blank=True, null=True, verbose_name='QR code data'),
        ),
    ]
