# Generated by Django 5.1.7 on 2025-03-17 17:25

from django.db import migrations
import uuid


def generate_qr_code_data(apps, schema_editor):
    """
    Generate unique UUIDs for the qr_code_data field of existing RSVP objects.
    """
    RSVP = apps.get_model('events', 'RSVP')
    for rsvp in RSVP.objects.all():
        rsvp.qr_code_data = uuid.uuid4()
        rsvp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rsvp_qr_code_data'),
    ]

    operations = [
        migrations.RunPython(generate_qr_code_data),
    ]
