# Generated by Django 5.1.7 on 2025-03-17 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_populate_qr_code_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='qr_code_data',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='QR code data'),
        ),
    ]
