# Generated by Django 5.1.7 on 2025-03-27 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_image'),
        ('userlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('email_template', models.TextField(blank=True, verbose_name='email template')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event')),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invitations', to='userlists.userlist')),
            ],
            options={
                'verbose_name': 'event invitation',
                'verbose_name_plural': 'event invitations',
                'ordering': ['-sent_at'],
                'unique_together': {('event', 'user_list')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='invited_lists',
            field=models.ManyToManyField(related_name='invited_to_events', through='events.EventInvitation', to='userlists.userlist', verbose_name='invited lists'),
        ),
    ]
