# Generated by Django 5.1.7 on 2025-03-27 07:04

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


def create_default_template(apps, schema_editor):
    EmailTemplate = apps.get_model('events', 'EmailTemplate')
    EventInvitation = apps.get_model('events', 'EventInvitation')
    
    # Create default template from existing content
    default_template = EmailTemplate.objects.create(
        name='Default Template',
        subject='{{ event.title }} - You\'re Invited!',
        content='''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            text-align: center;
            padding: 20px 0;
        }
        .event-image {
            width: 100%;
            max-width: 600px;
            height: auto;
            border-radius: 8px;
            margin: 20px 0;
        }
        .event-details {
            background-color: #f8f9fa;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
        }
        .button {
            display: inline-block;
            padding: 12px 24px;
            margin: 10px;
            border-radius: 25px;
            text-decoration: none;
            font-weight: bold;
            text-align: center;
        }
        .accept {
            background-color: #28a745;
            color: white;
        }
        .decline {
            background-color: #dc3545;
            color: white;
        }
        .app-stores {
            text-align: center;
            margin: 30px 0;
        }
        .app-button {
            display: inline-block;
            margin: 10px;
            max-width: 200px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>You're Invited!</h1>
        </div>

        <p>Dear {{ first_name }},</p>

        <p>You are cordially invited to:</p>
        
        <div class="event-details">
            <h2>{{ event.title }}</h2>
            {% if event.image %}
            <img src="{{ event.image.url }}" alt="{{ event.title }}" class="event-image">
            {% endif %}
            
            <h3>Event Details:</h3>
            <p><strong>Date:</strong> {{ event.date|date:"l, F j, Y" }}</p>
            <p><strong>Time:</strong> {{ event.date|date:"g:i A" }}</p>
            <p><strong>Location:</strong> {{ event.location }}</p>
            
            {% if event.description %}
            <h3>Description:</h3>
            <p>{{ event.description }}</p>
            {% endif %}
        </div>

        <div style="text-align: center;">
            <h3>Will you attend?</h3>
            <a href="{{ rsvp_accept_url }}" class="button accept">Accept</a>
            <a href="{{ rsvp_decline_url }}" class="button decline">Decline</a>
        </div>

        <div class="app-stores">
            <h3>Get the Moratwe App</h3>
            <p>Download our mobile app to manage your invitations and stay updated:</p>
            <div>
                <a href="https://apps.apple.com/app/moratwe" class="app-button">
                    <img src="https://moratwe.com/static/images/app-store-badge.png" alt="Download on the App Store" style="max-width: 200px;">
                </a>
            </div>
            <div>
                <a href="https://play.google.com/store/apps/details?id=com.moratwe.app" class="app-button">
                    <img src="https://moratwe.com/static/images/google-play-badge.png" alt="Get it on Google Play" style="max-width: 200px;">
                </a>
            </div>
        </div>

        <div class="footer">
            <p>This invitation was sent to you via Moratwe Events.</p>
            <p>If you have any questions, please contact us at support@moratwe.co.za</p>
        </div>
    </div>
</body>
</html>''',
        is_default=True,
        created_at=django.utils.timezone.now(),
        updated_at=django.utils.timezone.now()
    )
    
    # Update all existing invitations to use the default template
    EventInvitation.objects.all().update(email_template_id=default_template.id)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventinvitation_event_invited_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('subject', models.CharField(help_text='You can use {{ event.title }} in the subject', max_length=255, verbose_name='subject')),
                ('content', models.TextField(help_text='Available variables: {{ first_name }}, {{ last_name }}, {{ event.title }}, {{ event.date }}, {{ event.location }}, {{ event.description }}, {{ event.image }}, {{ rsvp_accept_url }}, {{ rsvp_decline_url }}', verbose_name='content')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'ordering': ['name'],
            },
        ),
        # First remove the old field
        migrations.RemoveField(
            model_name='eventinvitation',
            name='email_template',
        ),
        # Then add the new field
        migrations.AddField(
            model_name='eventinvitation',
            name='email_template',
            field=models.ForeignKey(blank=True, help_text='Select the email template to use for this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.emailtemplate', verbose_name='email template'),
        ),
        # Run the data migration
        migrations.RunPython(create_default_template),
    ]
