# Generated by Django 5.1.7 on 2025-03-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_emailtemplate_alter_eventinvitation_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitation',
            name='accepted_count',
            field=models.IntegerField(default=0, verbose_name='accepted'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='declined_count',
            field=models.IntegerField(default=0, verbose_name='declined'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='failed_count',
            field=models.IntegerField(default=0, verbose_name='failed'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last sent at'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='pending_count',
            field=models.IntegerField(default=0, verbose_name='pending'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='total_sent',
            field=models.IntegerField(default=0, verbose_name='total sent'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(help_text='Available variables: {{ first_name }}, {{ last_name }}, {{ event.title }}, {{ event.date }}, {{ event.location }}, {{ event.description }}', verbose_name='content'),
        ),
    ]
