# Generated by Django 5.1.7 on 2025-03-27 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventinvitation_accepted_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvp',
            options={'ordering': ['-created_at'], 'verbose_name': 'RSVP', 'verbose_name_plural': 'RSVPs'},
        ),
        migrations.RemoveField(
            model_name='eventinvitation',
            name='accepted_count',
        ),
        migrations.RemoveField(
            model_name='eventinvitation',
            name='declined_count',
        ),
        migrations.RemoveField(
            model_name='eventinvitation',
            name='failed_count',
        ),
        migrations.RemoveField(
            model_name='eventinvitation',
            name='last_sent_at',
        ),
        migrations.RemoveField(
            model_name='eventinvitation',
            name='pending_count',
        ),
        migrations.RemoveField(
            model_name='eventinvitation',
            name='total_sent',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_requirements',
            field=models.TextField(blank=True, verbose_name='dietary requirements'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='is_registered_user',
            field=models.BooleanField(default=False, verbose_name='is registered user'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=0, verbose_name='number of guests'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='response date'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('maybe', 'Maybe')], default='pending', max_length=10, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='selected_sessions',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='events.breakawaysession'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
