# Generated by Django 5.1.7 on 2025-03-27 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_rsvp_options_and_more'),
        ('userlists', '0004_remove_invitee_rsvp_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='invited_lists',
        ),
        migrations.CreateModel(
            name='InviteeRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10, verbose_name='status')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='timestamp')),
                ('token', models.UUIDField(blank=True, null=True, unique=True, verbose_name='token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee_rsvps', to='events.event')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='userlists.invitee')),
            ],
            options={
                'verbose_name': 'invitee RSVP',
                'verbose_name_plural': 'invitee RSVPs',
                'ordering': ['-created_at'],
                'unique_together': {('invitee', 'event')},
            },
        ),
    ]
