# Generated by Django 5.1.7 on 2025-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_invited_lists_inviteersvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('task_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('invitation', 'Send Invitations'), ('rsvp', 'Process RSVPs')], max_length=20)),
                ('event_id', models.IntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('pause', 'Paused'), ('complete', 'Complete'), ('stopped', 'Stopped'), ('error', 'Error')], default='running', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('offset', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Statuses',
                'ordering': ['-updated_at'],
            },
        ),
    ]
