# Generated by Django 5.1.7 on 2025-03-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteersvp',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether an invitation email has been sent', verbose_name='email sent'),
        ),
        migrations.AddField(
            model_name='inviteersvp',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email sent at'),
        ),
    ]
