# Generated by Django 5.1.7 on 2025-08-01 08:52

from django.db import migrations
from django.utils import timezone


def fix_rsvp_statuses(apps, schema_editor):
    """
    Fix RSVP statuses that are 'pending' but should be 'accepted' for users who
    responded to events without formal email invitations.
    """
    RSVP = apps.get_model('events', 'RSVP')
    
    # Find RSVPs that have 'pending' status but have a response_date,
    # which indicates the user actively responded
    pending_rsvps_with_response = RSVP.objects.filter(
        status='pending',
        response_date__isnull=False
    )
    
    # Update these to 'accepted' since they actively responded
    count = pending_rsvps_with_response.update(status='accepted')
    
    print(f"Fixed {count} RSVP records: changed status from 'pending' to 'accepted'")


def reverse_fix_rsvp_statuses(apps, schema_editor):
    """
    Reverse migration - not implementable since we can't determine which
    RSVPs were originally pending vs. those that were fixed.
    """
    # This is intentionally left as a no-op since we can't reliably reverse
    # the data migration without additional tracking
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_inviteersvp_email_sent_inviteersvp_email_sent_at'),
    ]

    operations = [
        migrations.RunPython(fix_rsvp_statuses, reverse_fix_rsvp_statuses),
    ]
