# Generated by Django 5.1.7 on 2025-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20250801_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='guest_category',
            field=models.CharField(choices=[('all', 'All Categories'), ('regular', 'Regular'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='all', help_text='Which guest category this template is designed for', max_length=10, verbose_name='Target Guest Category'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(help_text='Available variables: {{ first_name }}, {{ last_name }}, {{ event.title }}, {{ event.date }}, {{ event.location }}, {{ event.description }}, {{ guest_category }}', verbose_name='content'),
        ),
    ]
