# Generated by Django 5.1.7 on 2025-03-27 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitee',
            options={'ordering': ['email'], 'verbose_name': 'invitee', 'verbose_name_plural': 'invitees'},
        ),
        migrations.AlterModelOptions(
            name='userlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'user list', 'verbose_name_plural': 'user lists'},
        ),
        migrations.AddField(
            model_name='invitee',
            name='rsvp_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10, verbose_name='RSVP status'),
        ),
        migrations.AddField(
            model_name='invitee',
            name='rsvp_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='RSVP timestamp'),
        ),
        migrations.AddField(
            model_name='invitee',
            name='rsvp_token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='RSVP token'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
