# Generated by Django 5.1.7 on 2025-03-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlists', '0003_alter_invitee_options_alter_userlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitee',
            name='rsvp_status',
        ),
        migrations.RemoveField(
            model_name='invitee',
            name='rsvp_timestamp',
        ),
        migrations.RemoveField(
            model_name='invitee',
            name='rsvp_token',
        ),
    ]
