# Generated by Django 5.1.7 on 2025-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlists', '0004_remove_invitee_rsvp_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
