# Generated by Django 5.1.7 on 2025-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlists', '0005_alter_invitee_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='guest_category',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='regular', help_text='Guest categorization level (Regular, VIP, VVIP)', max_length=10, verbose_name='Guest Category'),
        ),
    ]
