# Generated by Django 5.1.7 on 2025-03-17 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, verbose_name='checked in at')),
            ],
            options={
                'verbose_name': 'check-in',
                'verbose_name_plural': 'check-ins',
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='code')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'check-in code',
                'verbose_name_plural': 'check-in codes',
            },
        ),
    ]
