# Generated by Django 5.1.7 on 2025-03-17 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkin', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checked_in_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_checkins', to=settings.AUTH_USER_MODEL, verbose_name='checked in by'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='event_attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='events.eventattendee', verbose_name='event attendee'),
        ),
        migrations.AddField(
            model_name='checkincode',
            name='event_attendee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_code', to='events.eventattendee', verbose_name='event attendee'),
        ),
    ]
