# Generated by Django 5.1.7 on 2025-03-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkincode',
            name='event_attendee',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='event_attendee',
        ),
    ]
