# Generated by Django 5.1.7 on 2025-03-17 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_remove_checkincode_event_attendee_and_more'),
        ('events', '0003_alter_event_options_remove_event_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='rsvp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='events.rsvp', verbose_name='RSVP'),
        ),
        migrations.DeleteModel(
            name='CheckInCode',
        ),
    ]
